<a href="https://colab.research.google.com/github/Skye-Gao/A2Z-F16/blob/gh-pages/%5BPublic%5D_Demo_2_Personal_Social_Posts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Workshop: Do it yourself!

**During this lab you will**:

- Run a sentiment classifier on your personal social media data (or a pre-defined set of posts if you prefer).

In [ ]:
!pip install transformers

Collecting transformers
  Downloading transformers-4.34.0-py3-none-any.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 66.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.4)
Collecting huggingface-hub<1.0,>=0.16.4 (from transformers)
  Downloading huggingface_hub-0.18.0-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 28.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.15,>=0.14 (from transformers)
  Downloading tokenizers-0.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 39.0 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers)
  Downloading safetensors-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.6 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Collecting huggingface-hub<1.0,>=0.16.4 (from transformers)
  Downloading huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 37.4 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.7.22)
Installing collected packages: safetensors, huggingface-hub, tokenizers, transformers
Successfully installed huggingface-hub-0.17.3 safetensors-0.4.0 tokenizers-0.14.1 transformers-4.34.0

In [ ]:
# https://huggingface.co/bhadresh-savani/bert-base-uncased-emotion

from transformers import pipeline
from pprint import pprint
import pandas as pd

def viz_predictions(texts):
    predictions = classifier(texts)
    data = []
    for text, pred in zip(texts, predictions):
        local_d = {'text': text}
        for pair in pred:
            local_d[pair['label']] = pair['score']
        data.append(local_d)
    return pd.DataFrame(data).style.background_gradient(cmap='Blues', axis=1)

classifier = pipeline("text-classification", model='bhadresh-savani/bert-base-uncased-emotion', return_all_scores=True)

Downloading (…)lve/main/config.json:   0%|          | 0.00/935 [00:00<?, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/285 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_classification.py:105: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [ ]:
prediction = classifier("I love using transformers. The best part is wide range of support and its easy to use", )
pprint(prediction)

[[{'label': 'sadness', 'score': 0.0005138233536854386},
  {'label': 'joy', 'score': 0.9972521662712097},
  {'label': 'love', 'score': 0.000744332792237401},
  {'label': 'anger', 'score': 0.0007404928910546005},
  {'label': 'fear', 'score': 0.0003293853369541466},
  {'label': 'surprise', 'score': 0.00041974865598604083}]]

In [ ]:
MIT_Confessions_posts = [
    "#64945 Give me the unearned confidence of men asking me out after I told them who I had a crush on to their face",
    "#64944 I saw you for the first time in the Infinite. You were walking in front of me and I couldn’t take my eyes off the back of your head. You were on your phone. You were walking slow. You were…infuriating.",
    "#64943 Gotta say I never expected the “she’s cheer captain and I’m on the bleachers” thing to follow me into college, but god damn I never stood a chance against her, did I? Excuse me while I scroll through her instagram and hate myself ",
    "#64942 how do the gym men grow boobies like that??? hgghhh ??? and where does this man find the time because i know for sure he's in like 2 hard grad classes ?????",
    "#64941 Those brownies and good vibes in lobby 10 really were the highlight of my day",
    """#64940 Prof: The degeneracy of the global minima is much higher than the degeneracy of the other critical points.
    Me: MIT has brought me to my global minimum""",
    "#64939 I miss handing in a physical pset. The dried tears just don't show up as well on these scanned submissions.",
    "#64938 What's the utility function for having fun? I gather the more foolish I am the more costly and more fun it would be. Please note that costs diminish over time due to people caring less as time increases. With this logic, I can have inf fun and be an asshole indefinitely, I could have small fun from week to week, or I could be the most saintly person ever and judge everyone else at the cost of never living. Work is a constant tho"
]

In [ ]:
viz_predictions(MIT_Confessions_posts)

In [ ]:
your_posts = [
    "my happy post",
    "my sad post",
    "what am i supposed to add here?"
]
viz_predictions(your_posts)